#spring.application.name=CourseManagement
server:
  port: 8080
  servlet:
    context-path: /course

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/course_management"
    username: root
    password: 123456